language: python

dist: trusty

python:
  - "3.6"      # current default Python on Travis CI

# command to install dependencies
install:
  - pip install flake8 pytest autopep8 pycodestyle pylint

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull

# command to run tests
script:
- pytest
# stop the build if there are Python syntax errors or undefined names
- flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
# exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
- flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
- pycodestyle --count --max-line-length=127 --statistics --exclude=venv ./sort
- pylint -f colorized --ignore-patterns=venv -r y ./sort
- autopep8 --recursive --in-place --aggressive --aggressive ./sort
