language: python

dist: trusty

python:
  - "3.6"      # current default Python on Travis CI
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull

# command to run tests
script: pytest
